include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - prefer_single_quotes
    - use_string_in_part_of_directives
    - require_trailing_commas

# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.y.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "coverage/**"
    - "build/**"

  errors:
    invalid_annotation_target: ignore # JsonKey warnings, see https://github.com/rrousselGit/freezed/issues/488
    non_constant_identifier_names: ignore

# You need to enable this to use the extension-methods.
#include: package:pedantic/analysis_options.yaml
#enable-experiment:
#  - extension-methods
