name: glassmorphism_ui
description: Create beautiful Glassmorphic ui using this components provided by this package
version: 0.1.0
author: Smile garg<imsmilegarg@gmail.com>
homepage: https://github.com/imsmilegarg/glassmorphism_ui.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

